platanus/bank-api-gem

Gemfile.lock
bank_api.gemspec
lib/bank_api.rb
lib/bank_api/clients/banco_de_chile_company_client.rb
lib/bank_api/clients/base_client.rb
lib/bank_api/configuration.rb
lib/bank_api/exceptions.rb
lib/bank_api/sign_deposits.rb
lib/bank_api/values/deposit_entry.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb
spec/bank_api/clients/base_client_spec.rb
spec/bank_api/sign_deposits_spec.rb
spec/bank_api_spec.rb

- Agrega opción de configuración por bloque de la gema
- Agrega dependencias de los clientes
- Agrega firma de depósitos
- Agrega BaseClient
- Agrega BancoDeChileCompanyClient

Banco de chile deposits

---

README.md

- Agrega instrucciones de uso al `README.md`

chore(): Add usage to readme

---

lib/bank_api.rb
lib/bank_api/clients/banco_security/company_client.rb
lib/bank_api/clients/base_client.rb
lib/bank_api/configs/banco_security.rb
lib/bank_api/configuration.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/base_client_spec.rb
spec/bank_api_spec.rb

- Se agrega el client para `BancoSecurity`. Hay código un poco feo (llamados a javascript directamente), la razón de esto es porque la página muy lenta, y a veces tira timeout cuando se espera la renderización de los frames. Por lo que se emula lo que se ejecutaría haciendo click en los botones renderizados.
- El client está dentro de un módulo, al igual que su configuración, sería bueno en un futuro hacer lo mismo para el Banco de Chile.

feat(): Add BancoSecurity's CompanyClient

---

lib/bank_api/clients/banco_de_chile_company_client.rb

- Se agrega paginación a `BankApi.get_bdc_recent_company_deposits`

fix(): Add deposits with paginations

---

lib/bank_api/clients/banco_security/company_client.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb
spec/bank_api/clients/banco_security/company_client_spec.rb

- Agregar tests de paginación para Banco de Chile
- Agregar paginación para Banco Security
HOLD: Falta probarlo una vez por lo menos con hartas transferencias

[HOLD] Banco security pagination

---

lib/bank_api/clients/banco_security/concerns/deposits.rb

- Se espera por el botón del form de los depósitos y luego se settea el tamaño de la página.

fix(banco_security): Wait for deposit form

---

lib/bank_api/clients/banco_security/company_client.rb
lib/bank_api/clients/banco_security/concerns/deposits.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/banco_security/concerns/deposits_spec.rb

- Se descarga un `.txt` con los depósitos en vez de paginar en el `BancoSecurity`

feat(): Use deposits txt to fetch deposits

---

lib/bank_api/clients/banco_security/concerns/deposits.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/banco_security/concerns/deposits_spec.rb

- Se le agregan los puntos a los ruts en los depósitos

feat(): Add dots to rut

---

lib/bank_api/clients/banco_security/concerns/deposits.rb

- Se hace un split antes de parsear el date

fix(banco_security/deposits): Remove time from date

---

lib/bank_api.rb
lib/bank_api/clients/banco_security/company_client.rb
lib/bank_api/clients/banco_security/concerns/balance.rb
lib/bank_api/clients/navigation/banco_security/company_navigation.rb
lib/bank_api/exceptions.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/banco_security/concerns/balance_spec.rb

- Se agrega la consulta por saldo al banco security, con `BankApi::BancoSecurity.get_account_balance(account_number)`

feat(): Security's account_balance

---

lib/bank_api/clients/banco_de_chile_company_client.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb

fix(banchileql): Ensure browser.close

---

lib/bank_api/clients/banco_de_chile_company_client.rb
lib/bank_api/configuration.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb

- Se seleciona la primera cuenta al ver depósitos
- Si sale el "no podemos atenderlos" tira un error

feat(banchile): Select first account on deposits

---

lib/bank_api.rb
lib/bank_api/clients/banco_de_chile_company_client.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb

@borismacias para probar desde fintual apunto la gema así: `gem 'bank_api', path: '/Users/leandro/src/bank-api-gem'` y en la consola de rails hago: `BankApi.get_bdc_recent_company_deposits(source: :account_details)`
Este PR, es parte de esta tarjeta: https://trello.com/c/QpzNeEbg/989-detector-de-errores-del-chile

feat(chile-bank): get deposits from account txt

---

lib/bank_api/clients/banco_security/concerns/deposits.rb

- Se agrega un `-` para resetear el datepicker antes de escribir

fix(): Add invalid character to reset datepicker

---

lib/bank_api/clients/banco_security/concerns/deposits.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/banco_security/concerns/deposits_spec.rb

- Fix para poder escribir en el datepicker del banco

refactor(): Add sleep between writing each char on security's datepicker

---

lib/bank_api/clients/banco_de_chile_company_client.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb

- Se manda una request para preparar los depósitos, y luego se manda la request para sacar el `txt`.

refactor(): Bypass transfers render on deposits fetch

---

lib/bank_api/clients/banco_security/concerns/deposits.rb
lib/bank_api/exceptions.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/banco_security/concerns/deposits_spec.rb

- Se tira un error si no encuentra depósitos

fix(banco-security): Raise error if can't fetch deposits

---

lib/bank_api.rb
lib/bank_api/clients/banco_security/company_client.rb
lib/bank_api/clients/banco_security/concerns/deposits.rb
lib/bank_api/clients/banco_security/concerns/session.rb
lib/bank_api/clients/banco_security/concerns/withdrawals.rb
lib/bank_api/clients/base_client.rb
lib/bank_api/clients/navigation/banco_security/company_navigation.rb
lib/bank_api/exceptions.rb
lib/bank_api/utils/banco_security.rb
lib/bank_api/values/withdrawal_entry.rb
spec/bank_api/clients/banco_security/company_client_spec.rb
spec/bank_api/clients/banco_security/concerns/withdrawals_spec.rb
spec/bank_api/clients/base_client_spec.rb

- Se agrega poder sacar las transferencias enviadas como `withdrawals`.

feat(): Security withdrawals

---

lib/bank_api.rb
lib/bank_api/clients/banco_de_chile_company_client.rb
lib/bank_api/utils/banco_de_chile.rb
spec/bank_api/clients/banco_de_chile_company_client_spec.rb
spec/bank_api_spec.rb

- Se sacan los retiros del banco de chile

Banchile withdrawals

---

lib/bank_api/clients/banco_security/company_client.rb
lib/bank_api/clients/banco_security/concerns/deposits.rb
lib/bank_api/exceptions.rb
spec/bank_api/clients/banco_security/company_client_spec.rb

- Se saca la validación por cantidad

refactor(security): Remove deposits quantity
